sudo: false
language: node_js
node_js:
- stable
script:
- npm run build
- npm test
deploy:
  provider: npm
  email: iwata0303@gmail.com
  on:
    tags: true
  skip_cleanup: true
  api_key:
    secure: RM/0xbQBZjs869SPtOmKHw7FfT7j3UnC07THlC8WmtemVUq/CTjam6Cysbe7F20Q/Wg8fDCol6e8mE7CyLesr/G3TG2EUeLQ1KP2ikedVBFsoByxf6WK6RcEdCKn+f8oyNTIpWzhXEeGtWzDi8lqyDDLBdDjd2YpbTiHX2UIcj1Q9piGFZtkx4JFZXRttgC4q/X3RHm4xUVaaJhPGnbkKLPnAqbvQmzMjNLorQIqn4oUhrAErmJ5d6Is6c0qZsxfUk8dQ/MOAJHm/s2wmQN9Ls8AdFu2YCMqhx2mjiGkIOsuejM0bCYp1RBFFev3aGnCfN8veaVOMSyDp2Duo0Ij1KsqXQif9kNXq+vn0Yi7v78lcg0TLAb+Ahksa2mLnMK2KrXGHaUzZruOgwPqyEhZMi22GSYp2iTi4VBrj6ouSxJhItPrV9iWgeOCrbxukt1NP4yUIP7Ea2JTqgEV2RH2HYjuZAaWB0GmIDjjvVk22cmOgMd0zEUzbYDQlf0u7xyX+S+8GaP3Boze9yB5lI3DHvUu0SkEDg4Tz6av5i+kawU55SW25HvlqR8KO/CxLCepmfZwyNTVxN4qB25Dn42RkwG2X1HkZzNSeX2PG3n3ulHKW3YmaaUHZhcNByy2761Xo1x0r3YbgpKJT3YpPROv7DN3ZEI71B8+8n3fOCCX1Es=
