sudo: false
language: node_js
node_js:
- stable
script:
- npm run build
- npm test
deploy:
  provider: npm
  email: iwata0303@gmail.com
  on:
    tags: true
  skip_cleanup: true
  api_key:
    secure: JPCslpZmRAItY5FofDwYHE2fBlQf6+rnSzYNC3Zm+jo644pPXhjab1VQwgLIyLxm41GIJmIFdQAOUzmP9ZRj4/fO6VbMBGJTxSKSi1Ee28IC7hX3FjuVcJ3K6IxqYaMdhN8drf96x5Gs8z98bBjugeVbaXpo7ZWSgxIuSJicMK3afd2xV+VC9TO9P4xup12plVABJPlbuUjNwduSyDRZg0Ty8Z/0DXWUOuYoJB6OHJuGACvP65EX34dSO8x3A/acmndLhQwVHNC4ufYQTDLs/8oyc4kLhVzzfVBpMaMVk8b/pZRSl1KrBraPJ3LaXZN5ymglpd7lMt5rGZA2SD9X3+6CVmOzIjs+reX7ggTJeCPEaeQgIzl2lDKa++wOT6HyPwICFKlzaZ5hg5tFF/qasH4qxJAXzTq+nOyvn8Qs5cKYACu8AnuAKtPcqpuJXl20vhtHLio0YZCWhick7Jczc5/zj8w7HZ+Kv9FwLjwFyfyWN8+kXzwPsDqkt5B0hMdIZsP/zfh8g7Mvl6evsegdGlYbcvEgMpUcaNo1I/NIq2qmFGbgbrVQSi41BTSB+c1p1dC6rnrI0368rJ/UCRSAqKkKQu/s+BDBhb7chVBge9k5RTaEfNHonLNYD9+iH9L4D8DhSkWM1n13jyeqQ9gnV7KWdYK8Xbp3h6e6jneKS0U=
